version: '3'
services:
  jenkins:
    container_name: jenkins_ansible
    image: jenkins_ansible
    build: 
      context: jenkins_ansible
    user: root
    ports:
      - 8080:8080
    volumes:
      - "$PWD/jenkins_ansible:/var/jenkins_home"
    networks:
      - jenkins_ansible_network
  node1:
    container_name: centos_host1
    image: centos_sshd
    build: 
      context: host1
    networks: 
      - jenkins_ansible_network
  node2:
    container_name: kibana
    image: centos_sshd
    networks: 
      - jenkins_ansible_network
    depends_on:
      - node1
    ports:
      - 5601:5601 
networks:
  jenkins_ansible_network: